spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cakecommentdb
    username: root
    password: test

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8082